"""Slope-specific compass-gait IC records for the Goswami cascade study.

The states below are post-impact coordinates
``(theta_ns, theta_s, dtheta_ns, dtheta_s)`` found by simulating the
existing :class:`CompassGait` return map from a perturbed phi=0.07 limit-cycle
state, then recording foot-strike reset states on the attracting return set.
For periodic slopes, fixed points are listed in return-map order.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import radians


State4 = tuple[float, float, float, float]


@dataclass(frozen=True)
class CompassGaitSlopeConfig:
    """Initial-condition record for a single compass-gait slope."""

    label: str
    phi_deg: float
    phi: float
    expected_period: int | None
    fixed_points: tuple[State4, ...] = ()
    sampling_cloud_path: str | None = None
    sampling_box: tuple[State4, State4] | None = None
    ic_sigma: float = 0.0
    project_to_post_impact_guard: bool = True
    source_note: str = ""


GOSWAMI_COMPASS_SLOPE_CONFIGS: dict[str, CompassGaitSlopeConfig] = {
    "phi_1": CompassGaitSlopeConfig(
        label="phi_1",
        phi_deg=4.75,
        phi=radians(4.75),
        expected_period=2,
        fixed_points=(
            (-0.381789947562, 0.215983668622, -0.153332476821, -1.153674078371),
            (-0.415364923432, 0.249558644492, -0.060946184320, -1.182371485198),
        ),
        ic_sigma=0.005,
        source_note="Goswami 1998 Fig. 10a period-2 gait.",
    ),
    "phi_2": CompassGaitSlopeConfig(
        label="phi_2",
        phi_deg=5.00,
        phi=radians(5.00),
        expected_period=4,
        fixed_points=(
            (-0.392348120036, 0.217815194837, -0.108006761939, -1.161444888863),
            (-0.427299657353, 0.252766732153, 0.000413424804, -1.184601376633),
            (-0.382352835289, 0.207819910089, -0.159748848674, -1.160346303620),
            (-0.429497351367, 0.254964426168, -0.028851139687, -1.201805735943),
        ),
        ic_sigma=0.0025,
        source_note="Goswami 1998 Fig. 10b period-4 gait.",
    ),
    "phi_3": CompassGaitSlopeConfig(
        label="phi_3",
        phi_deg=5.02,
        phi=radians(5.02),
        expected_period=8,
        fixed_points=(
            (-0.394646896303, 0.219415839402, -0.097321131256, -1.162198996812),
            (-0.427314643031, 0.252083586131, 0.005206094158, -1.182810887967),
            (-0.383158375915, 0.207927319015, -0.157853395670, -1.161234637529),
            (-0.430575865134, 0.255344808233, -0.023352371041, -1.201991305479),
            (-0.392070918536, 0.216839861636, -0.110015040931, -1.161935378338),
            (-0.428860635514, 0.253629578613, 0.004741355648, -1.186296239465),
            (-0.382063108952, 0.206832052052, -0.161190558173, -1.160743271438),
            (-0.430357289998, 0.255126233098, -0.029428533428, -1.204147661738),
        ),
        ic_sigma=0.0025,
        source_note="Goswami 1998 Fig. 10c period-8 gait.",
    ),
    "phi_4": CompassGaitSlopeConfig(
        label="phi_4",
        phi_deg=5.20,
        phi=radians(5.20),
        expected_period=None,
        sampling_box=(
            (-0.443352234088, 0.194065778691, -0.196436201372, -1.233962977088),
            (-0.375580020898, 0.261837991881, 0.080524179122, -1.161867693761),
        ),
        ic_sigma=0.0,
        source_note=(
            "Goswami 1998 Fig. 10d chaotic gait; box is a 1/99 percentile "
            "return-set envelope with 5 percent padding."
        ),
    ),
    "phi_4_cloud": CompassGaitSlopeConfig(
        label="phi_4_cloud",
        phi_deg=5.20,
        phi=radians(5.20),
        expected_period=None,
        sampling_cloud_path="chyll_v2/compass_analysis/compass_gait/phi_4_return_cloud.npy",
        ic_sigma=0.0,
        source_note=(
            "Goswami 1998 Fig. 10d chaotic gait; ICs sampled from an "
            "empirical post-impact return cloud generated by 4500 return-map "
            "strides with 500 burn-in at phi=5.20 deg."
        ),
    ),
}


def get_compass_slope_config(label: str) -> CompassGaitSlopeConfig:
    """Return a named Goswami slope config."""

    return GOSWAMI_COMPASS_SLOPE_CONFIGS[label]
